model:
  in_dim: 7
  out_dim: 2
  method: 39
  num_pipe: 3
  layers: [ 64, 64, 64, 64, 64 ]

  modes1: [ 25, 25, 25, 25 ]
  modes2: [ 25, 25, 25, 25 ]
  fc_dim: 128
  L_F_act: gelu
  num_pad: 4
  pad_ratio: [ 0,0.001,0 ]


train:
  mode: 'test'
  batchsize: 4
  Nsample: 500
  epochs: [ 300,5000 ]
  scheduler_step: 45
  learning_rate: 0.004
  milestones: [ 500,1000,1500,2000,2500,3000,3500,4000,4500,6000,7000,8000 ]
  scheduler_gamma: 0.5
  BC_loss: 0.2
  IC_loss: 0.1
  EQ_loss: 0.2

  save_dir: '3Y_gas'




